### ISSUE TITLE
Fix link detection

### ISSUE THREAD

**Issue by s-gv** [s-gv/orangeforum#47]
[Markdown](http://www.goodoldweb.com/) and/or <a href="http://www.goodoldweb.com/">html</a>; 

https://groups.goodoldweb.com/comments?id=24

**Comment by skx** [comment]
Using markdown would allow quoting to be supported easily, as per #5.

**Comment by s-gv** [comment]
The issue is because of HTML escaping. For example, `http://www.example.com/test&#34;` gets detected as a link and is rendered as `http://www.example.com/test"`. It should be fixed when markdown is supported #64.
