### ISSUE TITLE
Wiki?

### ISSUE THREAD

**Issue by kristofer** [s-gv/orangeforum#51]
Nice. Consider building a wiki next.

**Comment by s-gv** [comment]
Ok. I was thinking of mail server, but Wiki sounds good too. Do you have any particular use case in mind for a wiki?

**Comment by aravindhsampath** [comment]
+1 for building a simple wiki next! 
I was searching weeks for a simple wiki that will be used by just 20 users for internal documentation of processes and knowledge. Mediawiki is too complicated, feature heavy and old, other nice ones are locked in with some company. 

If you choose to build a wiki in the same style as orangeforum, I will happily contribute my spare time for anything related to it, and be your first paying contributor - I vouch $50 of personal money.

Here is what I'd like in such a modern wiki.
* Single binary to execute on the server.
* Option of using default SQLite or hooking up to an existing PostgreSQL.
* Ability to easily add syntax highlighted code. 
* Ability to drag and drop images into a wiki page.
* Full-text search.

Fancy features that can be useful in the future:
* Export as PDF/HTML/PNG
* External authentication using auth providers like AD and FreeIPA.
* Email subscriptions for updates on specific pages.

**Comment by s-gv** [comment]
@aravindhsampath Thanks! That's kind of you, and I appreciate the gesture. A wiki will be the next project in GoodOldWeb. I expect to get started on it next weekend.

I'll leave this issue open and post a link to the wiki repo when it's ready.

**Comment by s-gv** [comment]
@aravindhsampath Checkout Femtowiki. It is built with the same philosophy as Orangeforum: http://www.goodoldweb.com

The live demo is here: https://wiki.goodoldweb.com

I'm closing this issue here. If there are any issues related to the wiki, raise them at: https://github.com/s-gv/femtowiki
