### ISSUE TITLE
Feature request: Support for inline images

### ISSUE THREAD

**Issue by aravindhsampath** [s-gv/orangeforum#59]
The forum does feel like breathing fresh air in a polluted city. Thanks! 
I would love to use it as an internal forum if it had support for inline images (even great as drag & drop upload). My users (scientists) share too many charts in discussions, that they would not touch it without support for it. 
Not sure how hard it would be to implement, or if it is inline with the design goals of the project. Registering this issue as a feature request here to communicate a real need. Hope it helps.

**Comment by s-gv** [comment]
Images are supported, but they are disabled in the demo to ease moderation.

Login as the super admin > goto user profile (click on the username at the right-top of the screen) > admin section > enable images and configure data directory to store images.

To upload images, click on the reply button and select the image. The quick reply form at the bottom of the page doesn't accept images.

**Comment by s-gv** [comment]
The latest commit adds image upload from the quick reply box too. I'm closing this issue for now. Please re-open if you have any problem with image upload.
