### ISSUE TITLE
It doesn't let you type password

### ISSUE THREAD

**Issue by tural-esger** [s-gv/orangeforum#78]
$ ./orangeforum -createsuperuser
Creating superuser...
Username: tural
Password:
[ERROR] Password should have at least 8 characters.

as soon as you type username and hit enter it displays this error

**Comment by s-gv** [comment]
Can you share more details about what OS and terminal you are using? Does the issue happen only with the binary release or does it happen even if you compile locally?

Orangeforum uses the `golang.org/x/crypto/ssh/terminal` package to read the password from stdin. Can you reproduce the issue with this test program?

```
import (
    "fmt"
    "golang.org/x/crypto/ssh/terminal"
    "syscall"
)

func main() {
    password, err := terminal.ReadPassword(int(syscall.Stdin))
    if (err != nil) {
        fmt.Printf("[ERROR] %s\n", err)
    } else {
        fmt.Printf("password: %s\n", password)
    }
}
```

**Comment by tural-esger** [comment]
I am using windows 10 latest.
What I do is `go build` in the project directory.
Then I followed your readme.md 
Everything works nice except this one.

I reproduced the code snippet and it displayed what I typed in the terminal. It works.

I checked with all 3 terminal. Git terminal, cmd and powershell. They all displayed the same.

@s-gv Man you have done great job of writing this form. Thank you for your instant answer. I also created 3 websites using go. [engossip](https://engossip.com) is one of them. I liked in your project

- Structure

- not using framework

- codes you wrote. For example not only throwing listentandserve, but rather creating struct and defining timout and other things.
Your project caught my eyes. I wanna expore more and learn from your code. Thanks for everything.

**Comment by s-gv** [comment]
Thanks for the compliment. Perhaps the issue is with newline and fmt.Scan. I know CRLF is more common in Windows. Can you try this? (I don't have a copy of Windows at the moment)

```
import (
    "fmt"
    "golang.org/x/crypto/ssh/terminal"
    "syscall"
)

func main() {
    var userName string
    fmt.Printf("Username: ")
    fmt.Scan(&userName)
    password, err := terminal.ReadPassword(int(syscall.Stdin))
    if (err != nil) {
        fmt.Printf("[ERROR] %s\n", err)
    } else {
        fmt.Printf("user: %s -- password: %s\n", userName, password)
    }
}
```

**Comment by tural-esger** [comment]
I tried. The same. It doesn't wait me to type password and returns.

**Comment by s-gv** [comment]
It appears to be either Windows specific or due to CRLF usage. I wonder if this is related: https://github.com/golang/go/issues/8825

Can you try replacing `fmt.Scan(&userName)` with:

- `fmt.Scanf("%s\n", &userName)`
- `fmt.Scanln(&userName)`

**Comment by tural-esger** [comment]
Both of them worked. It means there is an issue with `  fmt.Scan(&userName)`
Thank you very much. So should we modify it to one of these in master ?

**Comment by s-gv** [comment]
Yes. I've changed it now.

**Comment by tural-esger** [comment]
@s-gv Thank you. I am going to pull.
