### ISSUE TITLE
security contact required for orangeforum

### ISSUE THREAD

**Issue by anticomputer** [s-gv/orangeforum#94]
Hello,

I am a member of the GitHub Security Lab team (https://securitylab.github.com). 

We've attempted to reach a maintainer for this project to report a potential security issue in orangeforum but have been unable to verify the report was received. If a project maintainer could drop us a line at securitylab@github.com in reference to GHSL-2020-126 we would like to further coordinate an appropriate response.

Kind Regards,
Bas Alberts
GitHub Security Lab

**Comment by s-gv** [comment]
I've received the report. Thanks for this effort you're putting into this. 

The branch you're referring to is no longer maintained.

**Comment by anticomputer** [comment]
> I've received the report. Thanks for this effort you're putting into this.
> 
> The branch you're referring to is no longer maintained.

@s-gv thank you for the response and update, we will mark it as a WONTFIX due to the branch no longer being maintained in favor of a new feature branch. We will note the new feature branch as an alternative in our report.
